<?php
/**
 * Created by PhpStorm.
 * User: sunwen
 * Date: 2018/3/19
 * Time: 16:11
 */
namespace app\common\controller;

use think\Controller;
use think\response\Json;

Class FraIndex extends Controller
{
    protected $json;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->json=array("res"=>0,"err"=>"","data"=>"");
    }

    protected function send($err=""){
        header("Access-Control-Allow-Origin: *");
        if(!empty($err)) $this->json["err"]=$err;
        if($this->json["res"]==1) $this->json["err"]="";
        $jmod=new Json($this->json);
        $jmod->send();
        die();
    }
}