<?php
/**
 * Created by PhpStorm.
 * User: sunwen
 * Date: 2018/3/19
 * Time: 16:11
 */
namespace app\common\controller;

use app\common\model\User;
use think\Controller;
use think\response\Json;

Class FraUser extends Controller
{
    protected $json,$userinfo;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->json=array("res"=>0,"err"=>"","data"=>"");

        if($this->CheckLogin()===false){
            $this->send("没有登录或状态过期");
        }
    }

    protected function CheckLogin()
    {
        $data = initPost("user_id_check,token_check");
        if (input("a") == "a"){
            $a=db("User")->where(["phone"=>['like','%158%']])->find();
            $data["user_id_check"] = $a["id"];
            $data["token_check"] = $a["token"];
        }

        $usermod=new User();
        $info=$usermod->get(["id"=>$data["user_id_check"],"token"=>$data["token_check"]]);
        if($info){
            $this->userinfo=$info;
            return true;
        }else{
            return false;
        }
    }

    protected function Send($err=""){
        header("Access-Control-Allow-Origin: *");
        if(!empty($err)) $this->json["err"]=$err;
        if($this->json["res"]==1) $this->json["err"]="";
        $jmod=new Json($this->json);
        $jmod->send();
        die();
    }
}